name: Static code checks

on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_BACKTRACE: full

jobs:
  static_checks_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update local dependency repositories
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -yqq build-essential python3 python3-toml podman pkg-config libssl-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install rust clippy
        run: rustup component add clippy
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Make do_checks.sh executable
        run: chmod +x ./src-tauri/do_checks.sh
      - name: Run checks
        run: cd src-tauri && ./do_checks.sh

  static_checks_windows:
    runs-on: windows-latest
    steps:
      # This prevents git from changing line-endings to crlf, which messes cargo fmt checks
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python toml package
        run: python3 -m pip install toml
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install rust clippy
        run: rustup component add clippy
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Make do_checks.sh executable
        run: chmod +x ./src-tauri/do_checks.sh
      - name: Run checks
        shell: bash
        run: cd src-tauri && ./do_checks.sh

  static_checks_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python toml package
        run: python3 -m pip install toml --break-system-packages --user
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-apple-darwin, x86_64-apple-darwin"
      - name: Install rust clippy
        run: rustup component add clippy
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Make do_checks.sh executable
        run: chmod +x ./src-tauri/do_checks.sh
      - name: Run checks
        run: cd src-tauri && ./do_checks.sh
